# Generated by Django 4.1.4 on 2023-03-05 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='img')),
                ('offer', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
