# Generated by Django 4.1.4 on 2023-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0002_product_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='imgages'),
        ),
    ]
