# Generated by Django 4.1.4 on 2023-03-06 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oral', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductDestination',
        ),
    ]
