# Generated by Django 4.1.4 on 2023-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0004_rename_product_productdestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdestination',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productdestination',
            name='option',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
    ]
