# Generated by Django 4.1.4 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0007_alter_productdestination_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdestination',
            name='option',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=100),
        ),
    ]
