# Generated by Django 4.1.4 on 2023-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0008_alter_productdestination_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdestination',
            name='option',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], default='draft', max_length=100),
        ),
    ]
